This notebook 
- requires 'reasons based dataset.csv' generated from '../Data Collection/reason-based-data.ipynb' 
- creates a 'complete data.csv' with columns ['Date', 'Fish', 'Fresh Type', 'Reason', 'S3_file_key'] from the images in the S3 bucket.
- creates a 'manual data.csv' from the images in the Manual Data folder with folder structure date/species/fish_type/img1.jpg
- then combines both manual data and s3 data files and stores in the 'complete data.csv' again. 
- this is created to store the metadata of our fish dataset with all the columns. This is useful to perform data analysis and generate reports without having to download the image data every time. We can also select specific dates and species, we are also saving time by skipping the already existing filenames.

In [ ]:
import os
import shutil
import boto3
import pandas as pd
from tqdm import tqdm
from datetime import datetime, timedelta

# Set the environment variables
# use your AWS credentials insted of these
os.environ['AWS_ACCESS_KEY_ID'] = ''
os.environ['AWS_SECRET_ACCESS_KEY'] = ''

In [ ]:
# filepath = r"/content/drive/MyDrive/Sowmya /qZense Dataset/Misclassified_data.txt"
# misclassified_folder_path = r"/content/drive/MyDrive/Sowmya /qZense Dataset/Misclassified"
# with open(filepath, 'w') as f:
#     for file in os.listdir(misclassified_folder_path):
#         f.write(file+'\n')

In [ ]:
# Replace the path below with the actual path to your Misclassified_data.txt file
filepath = r"/content/drive/MyDrive/Sowmya /qZense Dataset/Misclassified_data.txt"
with open(filepath, 'r') as f:
    misclassified = [line[:-1] for line in f]

In [ ]:
print(len(misclassified))

1519

In [ ]:
class S3DataDownloader:
    '''
    This class initializes the S3DataDownloader instance, lists all objects in the specified S3 bucket, groups them by their date extracted from their key, and replaces misspelled folder names with correct ones. It also reads a CSV file containing reasons for classifying the fish as 'bad' and stores it in a DataFrame for later use.
    '''
    def __init__(self, bucket_name, download_path, reasons_filepath):
        """
        Initializes the S3DataDownloader instance.

        Args:
            bucket_name (str): The name of the S3 bucket.
            download_path (str): The local directory to download files to.
        """
        self.bucket_name = bucket_name
        self.download_path = download_path
        # Create an S3 client
        self.s3_client = boto3.client('s3')
        self.grouped_objects = self.group_objects_by_date()
        self.reasons_df = pd.read_csv(reasons_filepath)

    def list_s3_objects(self, bucket_name=None):
        """
        Lists all objects in the specified S3 bucket.

        Args:
            bucket_name (str): The name of the S3 bucket.

        Returns:
            list: A list of objects in the S3 bucket.
        """
        if bucket_name is None:
            bucket_name = self.bucket_name
        object_list = []
        # Use a paginator to iterate through all the objects in the bucket
        paginator = self.s3_client.get_paginator('list_objects_v2')
        page_iterator = paginator.paginate(Bucket=bucket_name)

        for page in page_iterator:
            # Get the list of objects in the current page
            objects = page.get('Contents', [])
            object_list.extend(objects)
        print("\nlist_s3_objects done")
        return object_list

    def group_objects_by_date(self):
        """
        Lists all objects in the S3 bucket & groups them by their last modified date.

        Returns:
            dict: A dictionary where keys are dates and values are lists of object keys.
        """
        objects = self.list_s3_objects()
        grouped_objects = {}
        for obj in objects:
            key = obj['Key']

            # extracting date from key
            date = (key.split('/')[-1])[:8]
            date = date[:4] + '-' + date[4:6] + '-' + date[6:8]

            if date in grouped_objects:
                grouped_objects[date].append(key)
            else:
                grouped_objects[date] = [key]

        # Sort the dictionary based on date values in the keys
        grouped_objects = dict(sorted(grouped_objects.items(),
                                      key=lambda item: item[0]))
        print("group_objects_by_date done\n")
        return grouped_objects

    def replace_misspelled_folder_names(self, species_name):
        misspelled_folders = {
            'Are' : ['Ar', 'Are'],
            'Basa' : ['Basa', 'Basaa'],
            'Barracuda' : ['Barcoda', 'Barkoda', 'Barracoda', 'Barracuda'],
            'Bolo' : ['Bolo', 'Bulo'],
            'Catla' : ['Katala', 'Katalaa', 'Katla'],
            'Croaker' : ['Kokor', 'Croaker', 'Silver croaker'],
            'Chara pona' : ['Chara pana'],
            'Demo' : ['Demo', 'Demo2', 'Test', 'Trial'],
            'Emperor' : ['Comprel', 'Emperor', 'Emporwel', 'Empowel',
                         'M perl', 'M preal'],
            'Hilsa' : ['Hilsa', 'Hilis', 'Hilisa'],
            'Lady' : ['Lady', 'Ledi'],
            'Malabar trevally' : ['Mabar tavili', 'Malbhot', 'Travely', 'Travaily',
                                  'Trvili', 'Trevally', 'Travelly', 'Giant trevally'],
            'Needle' : ['Needale', 'Nidal', 'Nidil'],
            'Parsi' : ['Parci'],
            'Pearl spot' : ['(bloch,', 'Bloch,', 'Bloch',
                            'Pearl spot', 'Pearls spot', 'Hols spot',
                            'Green chromide', 'Green chormide',
                            'Hals spot'],
            'Sea bass' : ['C boss', 'C boos', 'Siba'],
            'Shol' : ['Sholo'],
            'Snapper' : ['Sinper', 'Sniper'],
            'White snapar' : ['White snapper'],
        }

        for key, misspellings in misspelled_folders.items():
            if species_name in misspellings:
                return key
        return species_name

In [ ]:
# Example usage
bucket_name='fish-data-collection-v2'
csv_filepath = '/content/drive/MyDrive/Sowmya /Data Collection/v5/complete data.csv'
reasons_filepath = '/content/drive/MyDrive/Sowmya /reasons Dataset/reasons_dataset.csv'

data_downloader=S3DataDownloader(bucket_name, csv_filepath, reasons_filepath)

list_s3_objects done
group_objects_by_date done

In [ ]:
self = data_downloader

In [ ]:
self.grouped_objects.keys()

dict_keys(['2023-05-18', '2023-05-19', '2023-05-20', '2023-05-23', '2023-05-25', '2023-05-26', '2023-05-27', '2023-05-28', '2023-05-30', '2023-06-01', '2023-06-02', '2023-06-03', '2023-06-04', '2023-06-06', '2023-06-08', '2023-06-09', '2023-06-10', '2023-06-11', '2023-06-12', '2023-06-13', '2023-06-15', '2023-06-16', '2023-06-17', '2023-06-18', '2023-06-20', '2023-06-22', '2023-06-23', '2023-06-24', '2023-06-25', '2023-06-27', '2023-06-29', '2023-06-30', '2023-07-01', '2023-07-02', '2023-07-04', '2023-07-06', '2023-07-07', '2023-07-08', '2023-07-09', '2023-07-11', '2023-07-13', '2023-07-14', '2023-07-15', '2023-07-16', '2023-07-18', '2023-07-20', '2023-07-22', '2023-07-23', '2023-07-25', '2023-07-27', '2023-07-28', '2023-07-29', '2023-07-30', '2023-08-01', '2023-08-03', '2023-08-04', '2023-08-05', '2023-08-06', '2023-08-08', '2023-08-09', '2023-08-10', '2023-08-11', '2023-08-12', '2023-08-13', '2023-08-15', '2023-08-17', '2023-08-18', '2023-08-19', '2023-08-20', '2023-08-22', '2023-08-24', '2023-08-25', '2023-08-26', '2023-08-27', '2023-08-29', '2023-08-31', '2023-09-01', '2023-09-02', '2023-09-03', '2023-09-06', '2023-09-07', '2023-09-08', '2023-09-09', '2023-09-10', '2023-09-12', '2023-09-14', '2023-09-15', '2023-09-16', '2023-09-19', '2023-09-21', '2023-09-22', '2023-09-23', '2023-09-24', '2023-09-26', '2023-09-28', '2023-09-29', '2023-09-30', '2023-10-02', '2023-10-03', '2023-10-05', '2023-10-06', '2023-10-07', '2023-10-08', '2023-10-10', '2023-10-12', '2023-10-13', '2023-10-14', '2023-10-15', '2023-10-19', '2023-10-20', '2023-10-21', '2023-10-24', '2023-10-25', '2023-10-26', '2023-10-27', '2023-10-28', '2023-10-29', '2023-10-31', '2023-11-01', '2023-11-02', '2023-11-03', '2023-11-04', '2023-11-07', '2023-11-09', '2023-11-10', '2023-11-14', '2023-11-15', '2023-11-16', '2023-11-17', '2023-11-18', '2023-11-19', '2023-11-21', '2023-11-22', '2023-11-23', '2023-11-25', '2023-11-28', '2023-11-29', '2023-11-30', '2023-12-01', '2023-12-02', '2023-12-03', '2023-12-05', '2023-12-06', '2023-12-07', '2023-12-08', '2023-12-09', '2023-12-10', '2023-12-12', '2023-12-13', '2023-12-14', '2023-12-15', '2023-12-16', '2023-12-17', '2023-12-19', '2023-12-22', '2023-12-23', '2023-12-24', '2023-12-26', '2023-12-27', '2023-12-28', '2023-12-29', '2023-12-30', '2023-12-31', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12', '2024-01-13', '2024-01-14', '2024-01-16', '2024-01-18', '2024-01-19', '2024-01-20', '2024-01-21', '2024-01-23', '2024-01-24', '2024-01-25', '2024-01-26', '2024-01-27', '2024-01-30', '2024-01-31', '2024-02-01', '2024-02-02', '2024-02-03', '2024-02-04', '2024-02-06', '2024-02-07', '2024-02-08', '2024-02-09', '2024-02-10', '2024-02-11', '2024-02-13', '2024-02-14', '2024-02-15', '2024-02-16', '2024-02-17', '2024-02-20', '2024-02-21', '2024-02-22', '2024-02-23', '2024-02-24', '2024-02-28', '2024-02-29', '2024-03-01', '2024-03-02', '2024-03-03', '2024-03-05', '2024-03-06', '2024-03-09', '2024-03-10', '2024-03-12', '2024-03-13', '2024-03-14', '2024-03-15', '2024-03-16', '2024-03-17', '2024-03-19', '2024-03-20', '2024-03-21', '2024-03-22', '2024-03-23', '2024-03-24', '2024-03-26', '2024-03-27', '2024-03-28', '2024-03-29', '2024-03-30', '2024-03-31', '2024-04-02', '2024-04-03', '2024-04-04', '2024-04-05', '2024-04-06', '2024-04-07', '2024-04-09', '2024-04-11', '2024-04-12', '2024-04-13', '2024-04-14', '2024-04-17', '2024-04-18', '2024-04-23', '2024-04-25', '2024-04-26', '2024-04-27', '2024-04-30', '2024-05-02', '2024-05-04', '2024-05-07', '2024-05-09', '2024-05-11', '2024-05-14', '2024-05-16', '2024-05-18', '2024-05-21', '2024-05-23', '2024-05-25', '2024-05-28', '2024-05-30', '2024-06-04', '2024-06-06', '2024-06-08', '2024-06-11', '2024-06-13', '2024-06-15', '2024-06-18', '2024-06-20', '2024-06-22', '2024-06-25', '2024-06-27', '2024-07-02', '2024-07-04', '2024-07-06', '2024-07-09', '2024-07-11', '2024-07-13', '2024-07-16', '2024-07-18', '2024-07-19', '2024-07-20', '2024-07-23', '2024-07-24', '2024-07-25', '2024-07-27', '2024-07-29', '2024-07-30', '2024-08-01', '2024-08-02', '2024-08-03', '2024-08-06', '2024-08-08', '2024-08-13', '2024-08-15', '2024-08-20', '2024-08-22', '2024-08-24', '2024-08-27', '2024-08-29', '2024-08-31', '2024-09-03', '2024-09-04', '2024-09-05', '2024-09-10', '2024-09-12', '2024-09-14', '2024-09-17', '2024-09-19', '2024-09-21', '2024-09-24', '2024-09-26', '2024-10-02', '2024-10-05', '2024-10-08', '2024-10-10', '2024-10-12', '2024-10-15', '2024-10-17', '2024-10-19', '2024-10-22', '2024-10-23', '2024-10-24', '2024-10-29', '2024-10-31', '2024-11-02', '2024-11-05', '2024-11-07', '2024-11-09', '2024-11-12', '2024-11-14', '2024-11-16', '2024-11-19', '2024-11-21', '2024-11-23', '2024-11-26', '2024-11-28', '2024-11-30', '2024-12-03', '2024-12-05', '2024-12-07', '2024-12-10', '2024-12-12', '2024-12-14', '2024-12-17', '2024-12-19', '2024-12-21', '2024-12-24', '2024-12-26', '2024-12-28', '2025-01-02', '2025-01-04', '2025-01-07', '2025-01-15', '2025-01-18', '2025-01-21', '2025-01-23', '2025-01-25', '2025-01-28', '2_ma-ck-er'])

In [ ]:
def create_dataframe(self, date, keys):
    '''
    This function downloads the images from the S3 bucket and creates a dataframe from the downloaded images
    '''
    
    if os.path.exists(self.download_path):
        df = pd.read_csv(self.download_path)
    else:
        columns=['Date', 'Filename', 'Species', 'Class', 'Reason',
                  'S3_file_key', 'BucketName']
        df = pd.DataFrame(columns=columns)

    stop = False

    # Iterate through the keys and extract fish name and fresh type from the image name and add it to the dataframe
    existing = set(df['Filename'].values)
    reason_lookup = (self.reasons_df.set_index("Filename")["description"].to_dict())

    for key in tqdm(keys, desc=f'Loading {date} data'):
        d = {}
        # Extract fish name and fresh type from the image name
        image_name = key.split('/')[-1]
        if image_name in existing:
            continue

        try:
            fish_name, fresh_type = image_name.split('_')[-2:]
        except:
            continue
        fresh_type = fresh_type.split('.')[0]
        fish_name = fish_name.capitalize()
        fresh_type = fresh_type.capitalize()
        fish_name = fish_name.strip()
        fresh_type = fresh_type.strip()
        fish_name = self.replace_misspelled_folder_names(fish_name)

        d['Date'] = date
        d['Filename'] = image_name
        d['Species'] = fish_name
        d['Class'] = fresh_type

        d['Reason'] = reason_lookup.get(image_name)
        d['S3_file_key'] = key

        if image_name in misclassified:
            d['Class'] = 'Misclassified'

        d['BucketName'] = self.bucket_name

        new_df = pd.DataFrame([d])
        df = pd.concat([df, new_df], ignore_index=True)
        df.to_csv(self.download_path, index=False)


def download_daily_data(self):
    for date, keys in self.grouped_objects.items():
        # if date<'2025-01-18':
        #     continue
        create_dataframe(self, date, keys)

In [ ]:
self.download_path = r'..\generated-files\complete data.csv'

In [ ]:
download_daily_data(self)

Loading 2025-01-18 data: 100%|██████████| 331/331 [00:00<00:00, 498.27it/s]
Loading 2025-01-21 data: 100%|██████████| 269/269 [00:00<00:00, 479.45it/s]
Loading 2025-01-23 data: 100%|██████████| 120/120 [00:00<00:00, 523.33it/s]
Loading 2025-01-25 data: 100%|██████████| 165/165 [00:00<00:00, 481.61it/s]
Loading 2025-01-28 data: 100%|██████████| 222/222 [03:44<00:00,  1.01s/it]
Loading 2_ma-ck-er data: 100%|██████████| 2/2 [00:00<00:00, 259.44it/s]

In [ ]:
# loaded_df = pd.read_csv('complete data.csv')
loaded_df = pd.read_csv(self.download_path)
loaded_df

,Date,Filename,Species,Class,Reason,S3_file_key,BucketName
0,2023-05-18,20230518085305657_mackerel_ok.jpeg,Mackerel,Ok,NaN,mackerel/ok/20230518085305657_mackerel_ok.jpeg,fish-data-collection-v2
1,2023-05-18,20230518084706566_rohu_good.jpeg,Rohu,Good,NaN,rohu/good/20230518084706566_rohu_good.jpeg,fish-data-collection-v2
2,2023-05-19,20230519071719731_mackerel_good.jpeg,Mackerel,Good,NaN,mackerel/good/20230519071719731_mackerel_good....,fish-data-collection-v2
3,2023-05-20,20230520121600220_indian salmon _good.jpeg,Indian salmon,Good,NaN,Indian salmon /good/20230520121600220_indian s...,fish-data-collection-v2
4,2023-05-20,20230520121628822_indian salmon _good.jpeg,Indian salmon,Good,NaN,Indian salmon /good/20230520121628822_indian s...,fish-data-collection-v2
...,...,...,...,...,...,...,...
89183,2025-01-28,20250128113440816_pink perch_bad.jpeg,Pink perch,Bad,Softness,pink perch/bad/20250128113440816_pink perch_ba...,fish-data-collection-v2
89184,2025-01-28,20250128113451297_pink perch_bad.jpeg,Pink perch,Bad,Softness,pink perch/bad/20250128113451297_pink perch_ba...,fish-data-collection-v2
89185,2025-01-28,20250128113459764_pink perch_bad.jpeg,Pink perch,Bad,Softness,pink perch/bad/20250128113459764_pink perch_ba...,fish-data-collection-v2
89186,2025-01-28,20250128113508768_pink perch_bad.jpeg,Pink perch,Bad,Softness,pink perch/bad/20250128113508768_pink perch_ba...,fish-data-collection-v2
89187,2025-01-28,20250128113518899_pink perch_bad.jpeg,Pink perch,Bad,Softness,pink perch/bad/20250128113518899_pink perch_ba...,fish-data-collection-v2

In [ ]:
self.download_path

'/content/drive/MyDrive/Sowmya /Data Collection/v5/complete data.csv'

In [ ]:
loaded_df['Reason'].value_counts()

Reason
Softness                                         19480
Manual_data                                       6211
Size                                               819
Cuts and Damage                                    632
Red Head in Prawns                                 473
Softness, Cuts and Damage                          460
Cuts and Damage, Softness                          442
Softness, Size                                     213
Size, Softness                                     192
Softness, Red Head in Prawns                       130
Cuts and Damage, Red Head in Prawns                109
Smell                                               88
Red Head in Prawns, Softness                        29
Size, Red Head in Prawns                            28
Red Head in Prawns, Cuts and Damage                 24
Softness, Color                                     21
Color                                               20
Softness, Smell                                     15
Size, Cuts and Damage                               13
Cuts and Damage, Size                               12
Cuts and Damage, Softness, Red Head in Prawns       12
Red Head in Prawns, Size                             9
Cuts and Damage, Size, Softness                      7
Color, Softness                                      6
Cuts and Damage, Red Head in Prawns, Softness        5
Softness, Size, Red Head in Prawns                   4
Softness, Cuts and Damage, Red Head in Prawns        4
Size, Softness, Cuts and Damage                      3
Smell, Softness                                      3
Cuts and Damage, Softness, Size                      3
Red Head in Prawns, Cuts and Damage, Softness        2
Size, Cuts and Damage, Softness                      2
Red Head in Prawns, Size, Softness                   2
Red Head in Prawns, Color                            2
Color, Size                                          2
Softness, Cuts and Damage, Size                      2
Color, Smell                                         2
Size, Color                                          2
Softness, Color, Red Head in Prawns                  2
Others, Softness                                     1
Red Head in Prawns, Softness, Cuts and Damage        1
Softness, Size, Cuts and Damage                      1
Softness, Red Head in Prawns, Smell                  1
Softness, Red Head in Prawns, Cuts and Damage        1
Softness, Cuts and Damage, Color                     1
Softness, Red Head in Prawns, Size                   1
Softness, Cuts and Damage, Smell                     1
Size, Cuts and Damage, Red Head in Prawns            1
Others                                               1
Smell, Color, Softness                               1
Name: count, dtype: int64

# Manual Data details

In [ ]:
'''
This script creates a dataframe from the manual data present in the folder structure and saves it to a CSV file. The folder structure is expected to be in the format: date/species/fresh_type/filename. If the CSV file already exists, it will be loaded and updated with any new files found in the folder structure. 

The resulting dataframe will contain columns for Date, Filename, Species, Class, and Reason.
'''

# path to the folder containing the manual data 
folder_path = 'Manual Data' 

# path to the csv file where the dataframe will be saved
csv_path = r'..\generated-files\manual data.csv' 


if os.path.exists(csv_path):
    df = pd.read_csv(csv_path)
else:
    columns=['Date', 'Filename', 'Species', 'Class', 'Reason']
    df = pd.DataFrame(columns=columns)

for date in os.listdir(folder_path):
    date_folder_path = os.path.join(folder_path, date)
    if not os.path.isdir(date_folder_path):
        continue
    for species in tqdm(os.listdir(date_folder_path), desc=f'{date}'):
        species_folder_path = os.path.join(date_folder_path, species)
        for fresh_type in os.listdir(species_folder_path):
            fresh_type_folder_path = os.path.join(species_folder_path, fresh_type)
            for filename in os.listdir(fresh_type_folder_path):
                file_path = os.path.join(fresh_type_folder_path, filename)
                file_dict = {'Date':date,
                             'Filename':filename,
                             'Species':species,
                             'Class':fresh_type,
                             'Reason':'Manual_data'}
                if filename in ['Single', 'Group']:
                    for img in os.listdir(file_path):
                        if img in df['Filename'].values:
                            continue
                        file_dict['Filename']=img
                        new_df = pd.DataFrame([file_dict])
                        df = pd.concat([df, new_df], ignore_index=True)
                        df.to_csv(csv_path, index=False)
                else:
                    if filename in df['Filename'].values:
                        continue
                    new_df = pd.DataFrame([file_dict])
                    df = pd.concat([df, new_df], ignore_index=True)
                    df.to_csv(csv_path, index=False)

df

2023-06-08: 100%|██████████| 2/2 [00:02<00:00,  1.31s/it]
2023-06-09: 100%|██████████| 2/2 [00:02<00:00,  1.10s/it]
2023-06-20: 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]
2023-06-22: 100%|██████████| 2/2 [00:02<00:00,  1.46s/it]
2023-07-25: 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]
2023-05-19: 100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
2023-05-20: 100%|██████████| 2/2 [00:02<00:00,  1.10s/it]
2023-05-18: 100%|██████████| 1/1 [00:01<00:00,  1.36s/it]
2023-05-23: 100%|██████████| 2/2 [00:02<00:00,  1.12s/it]
2023-12-21: 100%|██████████| 1/1 [00:01<00:00,  1.16s/it]
2024-02-27: 100%|██████████| 2/2 [00:04<00:00,  2.34s/it]
2024-01-17: 100%|██████████| 2/2 [00:03<00:00,  1.78s/it]
2024-06-13: 100%|██████████| 2/2 [00:02<00:00,  1.18s/it]
2024-06-27: 100%|██████████| 2/2 [00:02<00:00,  1.06s/it]
2024-06-29: 100%|██████████| 1/1 [00:01<00:00,  1.09s/it]
2024-07-11: 100%|██████████| 2/2 [00:03<00:00,  1.66s/it]
2024-07-18: 100%|██████████| 2/2 [00:02<00:00,  1.06s/it]
2024-08-13: 100%|██████████| 2/2 [00:02<00:00,  1.02s/it]
2024-08-24: 100%|██████████| 2/2 [00:02<00:00,  1.27s/it]
2024-08-27: 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]
2024-08-29: 0it [00:00, ?it/s]
2024-08-31: 100%|██████████| 1/1 [00:02<00:00,  2.23s/it]
2024-09-03: 100%|██████████| 1/1 [00:01<00:00,  1.06s/it]
2024-09-14: 100%|██████████| 1/1 [00:02<00:00,  2.34s/it]
2025-01-09: 100%|██████████| 3/3 [00:03<00:00,  1.15s/it]

            Date               Filename   Species Class       Reason
0     2023-06-08  IMG20230608080643.jpg  Mackerel  Good  Manual_data
1     2023-06-08  IMG20230608080649.jpg  Mackerel  Good  Manual_data
2     2023-06-08  IMG20230608080700.jpg  Mackerel  Good  Manual_data
3     2023-06-08  IMG20230608080655.jpg  Mackerel  Good  Manual_data
4     2023-06-08  IMG20230608080717.jpg  Mackerel  Good  Manual_data
...          ...                    ...       ...   ...          ...
6206  2025-01-09    20250109_130020.jpg  Mackerel  Good  Manual_data
6207  2025-01-09    20250109_130046.jpg  Mackerel  Good  Manual_data
6208  2025-01-09    20250109_130051.jpg  Mackerel  Good  Manual_data
6209  2025-01-09    20250109_125909.jpg  Mackerel  Good  Manual_data
6210  2025-01-09    20250109_130041.jpg  Mackerel  Good  Manual_data

[6211 rows x 5 columns]

# Combine Manual Data and S3 data details

In [ ]:
total_data_df = pd.read_csv(r'..\generated-files\complete data.csv')
total_data_df.shape

(88681, 7)

In [ ]:
manual_data_df = pd.read_csv(r'..\generated-files\manual data.csv')
manual_data_df.shape

(6211, 5)

In [ ]:
manual_data_df['Species'].unique()

array(['Mackerel', 'Sardine', 'White prawns'], dtype=object)

In [ ]:
new_df = pd.concat([total_data_df, manual_data_df], ignore_index=True)
new_df

,Date,Filename,Species,Class,Reason,S3_file_key,BucketName
0,2023-05-18,20230518085305657_mackerel_ok.jpeg,Mackerel,Ok,NaN,mackerel/ok/20230518085305657_mackerel_ok.jpeg,fish-data-collection-v2
1,2023-05-18,20230518084706566_rohu_good.jpeg,Rohu,Good,NaN,rohu/good/20230518084706566_rohu_good.jpeg,fish-data-collection-v2
2,2023-05-19,20230519071719731_mackerel_good.jpeg,Mackerel,Good,NaN,mackerel/good/20230519071719731_mackerel_good....,fish-data-collection-v2
3,2023-05-20,20230520121600220_indian salmon _good.jpeg,Indian salmon,Good,NaN,Indian salmon /good/20230520121600220_indian s...,fish-data-collection-v2
4,2023-05-20,20230520121628822_indian salmon _good.jpeg,Indian salmon,Good,NaN,Indian salmon /good/20230520121628822_indian s...,fish-data-collection-v2
...,...,...,...,...,...,...,...
94887,2025-01-09,20250109_130020.jpg,Mackerel,Good,Manual_data,NaN,NaN
94888,2025-01-09,20250109_130046.jpg,Mackerel,Good,Manual_data,NaN,NaN
94889,2025-01-09,20250109_130051.jpg,Mackerel,Good,Manual_data,NaN,NaN
94890,2025-01-09,20250109_125909.jpg,Mackerel,Good,Manual_data,NaN,NaN
94891,2025-01-09,20250109_130041.jpg,Mackerel,Good,Manual_data,NaN,NaN

In [ ]:
new_df.drop_duplicates(inplace=True)
new_df.shape

(88681, 7)

In [ ]:
new_df.to_csv(r'..\generated-files\complete data.csv', index=False)

In [ ]:
new_df = pd.read_csv(r'..\generated-files\complete data.csv')
new_df

,Date,Filename,Species,Class,Reason,S3_file_key,BucketName
0,2023-05-18,20230518085305657_mackerel_ok.jpeg,Mackerel,Ok,NaN,mackerel/ok/20230518085305657_mackerel_ok.jpeg,fish-data-collection-v2
1,2023-05-18,20230518084706566_rohu_good.jpeg,Rohu,Good,NaN,rohu/good/20230518084706566_rohu_good.jpeg,fish-data-collection-v2
2,2023-05-19,20230519071719731_mackerel_good.jpeg,Mackerel,Good,NaN,mackerel/good/20230519071719731_mackerel_good....,fish-data-collection-v2
3,2023-05-20,20230520121600220_indian salmon _good.jpeg,Indian salmon,Good,NaN,Indian salmon /good/20230520121600220_indian s...,fish-data-collection-v2
4,2023-05-20,20230520121628822_indian salmon _good.jpeg,Indian salmon,Good,NaN,Indian salmon /good/20230520121628822_indian s...,fish-data-collection-v2
...,...,...,...,...,...,...,...
88676,2025-01-21,20250121110117647_sardine_good.jpeg,Sardine,Good,NaN,sardine/good/20250121110117647_sardine_good.jpeg,fish-data-collection-v2
88677,2025-01-21,20250121110128356_sardine_good.jpeg,Sardine,Good,NaN,sardine/good/20250121110128356_sardine_good.jpeg,fish-data-collection-v2
88678,2025-01-21,20250121110140342_sardine_good.jpeg,Sardine,Good,NaN,sardine/good/20250121110140342_sardine_good.jpeg,fish-data-collection-v2
88679,2025-01-21,20250121110239996_sardine_good.jpeg,Sardine,Good,NaN,sardine/good/20250121110239996_sardine_good.jpeg,fish-data-collection-v2
88680,2025-01-21,20250121102457010_tuna_good.jpeg,Tuna,Good,NaN,tuna/good/20250121102457010_tuna_good.jpeg,fish-data-collection-v2